### ISSUE TITLE
BUG: When no results are returned, it gives a error that the site could not be accesed

### ISSUE THREAD

**Issue by agent255** [redelka00/stream-cli#13]
this is the exact error:
```
Unable to connect to torrent provider. Please use vpn. Exiting...
```
reproduce it by searching for something random

**Comment by eduardo-rdgz** [comment]
Your internet provider might be blocking the site. Try accessing the torrent site in the browser (https://torrentgalaxy.to).

**Comment by miniclip8767** [comment]
I've had this same issue. Attempting to connect to the site in the browser just throws a connection reset error.

**Comment by th3r00t** [comment]
try with a vpn connection

**Comment by redelka00** [comment]
> this is the exact error:
> 
> ```
> Unable to connect to torrent provider. Please use vpn. Exiting...
> ```
> 
> reproduce it by searching for something random

so should we give a hint that the issue might be a search or not exists as well as vpn!

**Comment by agent255** [comment]
Yeah 

> Your internet provider might be blocking the site. Try accessing the torrent site in the browser (https://torrentgalaxy.to).



> try with a vpn connection

i have my vpn on and i specified it only happens when you search for something random

**Comment by agent255** [comment]
> 

Yeah this would be nice
ill make a pr

**Comment by redelka00** [comment]
> > 
> 
> Yeah this would be nice
> ill make a pr

It's all yours.
