### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by agent255** [redelka00/stream-cli#14]
Currently on my windows 11 laptop the venv creation does not work.

**Comment by aquib-sh** [comment]
Can you confirm if it runs without venv creation on your Windows 11?

**Comment by redelka00** [comment]
> Try running `pip install virtualenv` then `virtualenv venv && .\venv\Scripts\activate`

This should work on windows the issue will be closed.
also if you need more info [here](https://github.com/redelka00/stream-cli/blob/main/docs/windowsVenv.md)
