### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ejlocop** [redelka00/stream-cli#17]
Got this error when running `python -m venv venv && source venv/bin/activate`.

I'm using windows 10 and running the command using Git Bash console.
![image](https://user-images.githubusercontent.com/12082880/166866200-5e76e847-4014-4844-9a3b-f5ec17bf55e7.png)

**Comment by redelka00** [comment]
Try to execute it line by line to see what happens, if you are in windows
`pip install virtualenv`
`cd stream-cli virtualenv --python C:\Path\To\Python\python.exe`
Then activate it with
`.\venv\Scripts\activate`

[Read more](https://mothergeo-py.readthedocs.io/en/latest/development/how-to/venv-win.html)

**Comment by ejlocop** [comment]
@redelka00 , it seemed to worked when I ran that.

```
created virtual environment CPython3.10.4.final.0-64 in 3799ms
  creator CPython3Windows(dest=D:\Projects\stream-cli\.venvScriptsactivate, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\tealiedie\AppData\Local\pypa\virtualenv)
    added seed packages: pip==22.0.4, setuptools==62.1.0, wheel==0.37.1
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
(venv) 
```

but after running `python main.py top` and entered the index of the movie, I got this error..
```
Traceback (most recent call last):
  File "D:\Projects\stream-cli\main.py", line 54, in <module>
    app()
  File "D:\Projects\stream-cli\venv\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "D:\Projects\stream-cli\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Projects\stream-cli\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Projects\stream-cli\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Projects\stream-cli\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Projects\stream-cli\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Projects\stream-cli\venv\lib\site-packages\typer\main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "D:\Projects\stream-cli\main.py", line 32, in top
    apprun(TopMoviesSpider, True)
  File "D:\Projects\stream-cli\main.py", line 26, in apprun
    stream(magnet, default_player=player)
  File "D:\Projects\stream-cli\src\stream.py", line 29, in stream
    subprocess.run(["webtorrent", magnet, f"--{default_player}"], check=True)
  File "C:\Users\tealiedie\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\tealiedie\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\tealiedie\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
(venv)
```

**Comment by Golden12finch** [comment]
> Try to execute it line by line to see what happens, if you are in windows `pip install virtualenv` `cd stream-cli virtualenv --python C:\Path\To\Python\python.exe` Then activate it with `.\venv\Scripts\activate`
> 
> [Read more](https://mothergeo-py.readthedocs.io/en/latest/development/how-to/venv-win.html)

After using this command am getting the error bash: cd: too many arguments
![Screenshot 2022-05-05 140449](https://user-images.githubusercontent.com/74141281/166888437-8d7aaf07-2dd5-4ad1-a1e5-1aaeb24fdc73.png)

**Comment by aquib-sh** [comment]
You can run it without creating a virtualenv, just pip install -r requirements.txt

**Comment by Golden12finch** [comment]
> You can run it without creating a virtualenv, just pip install -r requirements.txt

Thanks buddy it worked for me!

**Comment by Golden12finch** [comment]
> @redelka00 , it seemed to worked when I ran that.
> 
> ```
> created virtual environment CPython3.10.4.final.0-64 in 3799ms
>   creator CPython3Windows(dest=D:\Projects\stream-cli\.venvScriptsactivate, clear=False, no_vcs_ignore=False, global=False)
>   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\tealiedie\AppData\Local\pypa\virtualenv)
>     added seed packages: pip==22.0.4, setuptools==62.1.0, wheel==0.37.1
>   activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
> (venv) 
> ```
> 
> but after running `python main.py top` and entered the index of the movie, I got this error..
> 
> ```
> Traceback (most recent call last):
>   File "D:\Projects\stream-cli\main.py", line 54, in <module>
>     app()
>   File "D:\Projects\stream-cli\venv\lib\site-packages\typer\main.py", line 214, in __call__
>     return get_command(self)(*args, **kwargs)
>   File "D:\Projects\stream-cli\venv\lib\site-packages\click\core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "D:\Projects\stream-cli\venv\lib\site-packages\click\core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "D:\Projects\stream-cli\venv\lib\site-packages\click\core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "D:\Projects\stream-cli\venv\lib\site-packages\click\core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "D:\Projects\stream-cli\venv\lib\site-packages\click\core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "D:\Projects\stream-cli\venv\lib\site-packages\typer\main.py", line 500, in wrapper
>     return callback(**use_params)  # type: ignore
>   File "D:\Projects\stream-cli\main.py", line 32, in top
>     apprun(TopMoviesSpider, True)
>   File "D:\Projects\stream-cli\main.py", line 26, in apprun
>     stream(magnet, default_player=player)
>   File "D:\Projects\stream-cli\src\stream.py", line 29, in stream
>     subprocess.run(["webtorrent", magnet, f"--{default_player}"], check=True)
>   File "C:\Users\tealiedie\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "C:\Users\tealiedie\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Users\tealiedie\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> (venv)
> ```

Am getting the same issue

**Comment by redelka00** [comment]
##### This issue is about creating and setting up a vietualenv in windows.
I wrote a simple instruction for it [here](https://github.com/redelka00/stream-cli/blob/main/docs/windowsVenv.md)
