### ISSUE TITLE
ModuleNotFound error: No module called "scrapy"

### ISSUE THREAD

**Issue by sushi-sama** [redelka00/stream-cli#18]
Getting the following error when trying to set VLC as the player. (NOTE: I am using windows 10 and i have already run the requirements.txt file)
![image](https://user-images.githubusercontent.com/54070955/166887752-7e67e78e-9173-45db-a61f-f49dcfbf78fe.png)

**Comment by aquib-sh** [comment]
did you try to pip install it manually?

**Comment by sushi-sama** [comment]
i did inside the virtual environment (venv), which btw i had to start by running activation.bat since Windows does not have 'source' command (is that ok?). Should I try installing scrapy outside the virtual environment? What about the other modules in requirements.txt?

**Comment by aquib-sh** [comment]
you can run it even without virtualenv, try pip install -r requirements.txt without a venv

**Comment by sushi-sama** [comment]
yup ty, that seems to work
![image](https://user-images.githubusercontent.com/54070955/166892642-1edc253d-96a7-4d18-a989-a302e295888d.png)
What is the point of a venv? What do I loose out of not being able to use it?

**Comment by aquib-sh** [comment]
@sushi-sama venv helps you manage dependencies, when there are multiple applications depending on the different versions of the same module then if one of them have any breaking changes then it can break the script. But if you don't run multiple apps with the extreme different version of the same module then you don't need to worry much about venv.
