### ISSUE TITLE
Change `Unable to connect to torrent provider...` error if movie not found

### ISSUE THREAD

**Issue by Aymane11** [redelka00/stream-cli#25]
There's an issue with the `Unable to connect to torrent provider. Please use vpn. Exiting...` message.
It is displayed even if the crawler didn't find the movie (for example, looking for a fictional movie name).

I suggest adding a ping to the website before displaying the message to check whether it's a connection issue or the movie is not found, then display a message accordingly.

The [code](https://github.com/redelka00/stream-cli/blob/ffe3220d67b0d1b164604013ae733e033aedc12d/src/runner.py#L25) to change:
```python
if spider_class.output == []:
        utils.clear_screen()
        sys.exit(
            "\033[91mUnable to connect to torrent provider. Please use vpn. Exiting...\033[0m"
        )
```

**Comment by redelka00** [comment]
yes I just worked on it, I find out another way if he called the top movies option then there's no way a movie can be wrong, and for the search option, I'll add a Hint for it.
if you have a better solution feel free to make a PR

**Comment by redelka00** [comment]
> adding a ping to the website before displaying

Aaah okay understood nice trick.

**Comment by redelka00** [comment]
Done!
