### ISSUE TITLE
After selecting option number from top list, movie is not playing 

### ISSUE THREAD

**Issue by karankc23** [redelka00/stream-cli#27]
After selecting the option number from the top list, the movie is not playing. 
![Screenshot from 2022-05-06 17-36-07](https://user-images.githubusercontent.com/76587341/167128393-7b469943-f23f-4fb5-aba2-ab3e7ef4c7cd.png)

**Comment by nelsonchen5** [comment]
+1

**Comment by redelka00** [comment]
[SOLVED]
thanks for reporting.

**Comment by redelka00** [comment]
you can just use type `git pull`
