### ISSUE TITLE
test the app on macos and windows

### ISSUE THREAD

**Issue by redelka00** [redelka00/stream-cli#8]
the app is tested under a linux machine, looking forward for feedbacks from windows and osx users

**Comment by erwaen** [comment]
On mac os it seem that nothing happens when i select a option.. it's say fetching and then exiting...
<img width="700" alt="image" src="https://user-images.githubusercontent.com/59094130/166615538-7c6e1059-0515-4d66-abb0-2cd8bcf931d8.png">

**Comment by redelka00** [comment]
Do you have vlc or mpv?

**Comment by erwaen** [comment]
sorry its was because i dont have vlc or mpv

**Comment by erwaen** [comment]
i just download vlc and change de data file player.txt to 'vlc' because i put mpv to be the default,

maybe a good option will always ask to the user which player he wants to use and not save a default.

**Comment by redelka00** [comment]
> sorry its was because i dont have vlc or mpv

Can you install one of them and give us a feedback?

**Comment by erwaen** [comment]
yees its work, i try recently with vlc in my macbook air M1, not problem, its work really fast!

**Comment by erwaen** [comment]
![image](https://user-images.githubusercontent.com/59094130/166709226-db991119-6f0b-4633-86c4-b22887b0041e.png)

**Comment by redelka00** [comment]
> yees its work, i try recently with vlc in my macbook air M1, not problem, its work really fast!
> 
> 

I'm glad that you like it.
Closed for macos!
